//! Step 3e — `decode_subframe` against **real libFLAC frames**.
//!
//! Table: `tests/subframe_body_vectors.txt`, generated by
//! `scripts/gen_frame_vectors.sh` (independent `Bits` walk for field ground
//! truth + `flac -d` reference PCM; fail-closed per-stream kind censuses —
//! a libFLAC upgrade that changes a vector's type refuses to write the
//! table). Same rule as every layout test here since the 31-bit post-mortem:
//! encoder bytes witness layout; hand-packed bytes record belief.
//!
//! Four witnesses per body vector, in the order the decoder must earn them:
//!
//!   1. the dispatch outcome — returned `SubframeType` equals the table's
//!      `subframe_kind`/`subframe_order`;
//!   2. the warm-up read — `state` holds `warm_up_stream_order` reversed
//!      (most-recent-first), and the output prefix equals it in stream
//!      order (the 3a finding: warm-up IS the block's own first samples);
//!   3. the exit cursor — `bit_position()` equals the oracle walk's
//!      `exit_bits`, so every field width *below* the header (wasted run,
//!      warm-up, LPC precision/shift/coefficients, residual partitions) is
//!      pinned by arithmetic, not by a same-file oracle;
//!   4. the samples themselves — the decoded block equals `pcm_samples`,
//!      which came from the reference DECODER (`flac -d`), so
//!      reconstruction is witnessed by a second decoder, bit-exact.
//!
//! Rejections (precision `0b1111`, negative shift) cannot be
//! encoder-witnessed — libFLAC never emits them — so they mutate ONE field
//! of the real `lpc-256` frame at runtime, exactly as the header tests
//! mutate real headers. Bit positions for the mutations are derived from
//! the vector's own witnessed fields (header cursor + wasted + order ×
//! subframe bits), never hardcoded.

use flac_lite::Error;
use flac_lite::bits::BitReader;
use flac_lite::frame::{FrameHeader, StreamDefaults};
use flac_lite::subframe::{PredictorState, SubframeType, decode_subframe};

#[derive(Debug)]
struct BodyVector {
    label: String,
    frame: Vec<u8>,
    stream_samplerate_hz: u64,
    stream_bits_per_sample: u64,
    blocksize: u64,
    kind: String,
    order: u64,
    wasted: u64,
    subframe_bits: u64,
    warm_up_stream_order: Vec<i64>,
    lpc_precision_minus_one: Option<u64>,
    lpc_shift: Option<i64>,
    exit_bits: u64,
    pcm_samples: Vec<i64>,
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    text.split_whitespace()
        .map(|byte| {
            u8::from_str_radix(byte, 16)
                .unwrap_or_else(|e| panic!("vector has a non-hex byte {byte:?}: {e}"))
        })
        .collect()
}

fn ints(text: &str) -> Vec<i64> {
    if text.trim().is_empty() {
        return Vec::new();
    }
    text.split_whitespace()
        .map(|v| {
            v.parse::<i64>()
                .unwrap_or_else(|e| panic!("not an integer {v:?}: {e}"))
        })
        .collect()
}

fn load_body_vectors() -> Vec<BodyVector> {
    let table = include_str!("subframe_body_vectors.txt");
    let mut out: Vec<BodyVector> = Vec::new();

    for line in table.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Key-only lines are legal here: `warm_up_stream_order` carries an
        // empty value for order-0 vectors (verbatim/constant). The header
        // table has no such field, which is why its loader never met one.
        let (key, value) = line.split_once(char::is_whitespace).unwrap_or((line, ""));
        let value = value.trim();
        if key == "body_vector" {
            out.push(BodyVector {
                label: value.to_string(),
                frame: Vec::new(),
                stream_samplerate_hz: 0,
                stream_bits_per_sample: 0,
                blocksize: 0,
                kind: String::new(),
                order: 0,
                wasted: 0,
                subframe_bits: 0,
                warm_up_stream_order: Vec::new(),
                lpc_precision_minus_one: None,
                lpc_shift: None,
                exit_bits: 0,
                pcm_samples: Vec::new(),
            });
            continue;
        }
        let v = out
            .last_mut()
            .unwrap_or_else(|| panic!("body field {key:?} outside a body_vector block"));
        let number = || {
            value
                .strip_prefix("0x")
                .and_then(|h| u64::from_str_radix(h, 16).ok())
                .or_else(|| {
                    value
                        .parse::<i64>()
                        .ok()
                        .and_then(|x| u64::try_from(x).ok())
                })
                .unwrap_or_else(|| panic!("{}: not a number: {value:?}", v.label))
        };
        match key {
            "frame_hex" => v.frame = hex_to_bytes(value),
            "stream_samplerate_hz" => v.stream_samplerate_hz = number(),
            "stream_bits_per_sample" => v.stream_bits_per_sample = number(),
            "blocksize" => v.blocksize = number(),
            "subframe_kind" => v.kind = value.to_string(),
            "subframe_order" => v.order = number(),
            "subframe_wasted" => v.wasted = number(),
            "subframe_bits" => v.subframe_bits = number(),
            "warm_up_stream_order" => v.warm_up_stream_order = ints(value),
            "lpc_precision_minus_one" => v.lpc_precision_minus_one = Some(number()),
            "lpc_shift" => {
                v.lpc_shift = Some(
                    value
                        .parse::<i64>()
                        .unwrap_or_else(|e| panic!("{}: bad shift: {e}", v.label)),
                )
            }
            "exit_bits" => v.exit_bits = number(),
            "pcm_samples" => v.pcm_samples = ints(value),
            _ => {}
        }
    }
    assert!(!out.is_empty(), "body vector table contained no vectors");
    out
}

fn defaults(v: &BodyVector) -> StreamDefaults {
    StreamDefaults {
        sample_rate_hz: v.stream_samplerate_hz as u32,
        bits_per_sample: v.stream_bits_per_sample as u8,
    }
}

fn expected_type(v: &BodyVector) -> SubframeType {
    match v.kind.as_str() {
        "constant" => SubframeType::Constant,
        "verbatim" => SubframeType::Verbatim,
        "fixed" => SubframeType::Fixed(v.order as u8),
        "lpc" => SubframeType::Lpc {
            order: v.order as u8,
        },
        other => panic!("{}: unknown kind {other:?}", v.label),
    }
}

/// Parse the frame header (witnessed by `frame_header_layout.rs`) and leave
/// the reader on the subframe's first bit.
fn frame_reader(v: &BodyVector) -> (BitReader<'_>, FrameHeader) {
    let mut reader = BitReader::new(&v.frame);
    let header = FrameHeader::parse(&mut reader, &defaults(v))
        .unwrap_or_else(|e| panic!("{}: header parse failed: {e:?}", v.label));
    assert_eq!(
        header.blocksize, v.blocksize as usize,
        "{}: table blocksize disagrees with the parsed header",
        v.label
    );
    (reader, header)
}

/// The four witnesses, per body vector.
#[test]
fn decode_subframe_matches_the_body_vectors() {
    let vectors = load_body_vectors();

    // Coverage tripwire (same shape as the subframe-header suite's wasted
    // check): the four required kinds must all be present. If a required
    // vector ever drops, this fires instead of the suite silently
    // degrading to whichever types remain.
    for kind in ["verbatim", "constant", "fixed", "lpc"] {
        assert!(
            vectors.iter().any(|v| v.kind == kind),
            "body table has no {kind} vector — regenerate with \
             scripts/gen_frame_vectors.sh"
        );
    }
    assert!(
        vectors.iter().any(|v| v.wasted == 5),
        "body table has no wasted-bits vector (fixed1-wasted5-256 expected)"
    );

    for v in &vectors {
        let what = format!("vector {}", v.label);
        let (mut reader, header) = frame_reader(v);
        let mut state = PredictorState::new();
        let mut out = vec![0i32; v.blocksize as usize];

        let kind = decode_subframe(
            &mut reader,
            header.blocksize,
            header.bits_per_sample,
            &mut state,
            &mut out,
        )
        .unwrap_or_else(|e| panic!("{what}: decode_subframe failed: {e:?}"));

        // 1. dispatch outcome
        assert_eq!(kind, expected_type(v), "{what}: subframe type");

        // 2. warm-up: the state holds the CODED (wasted-stripped) values,
        // most-recent-first — prediction runs at the coded scale (§9.2.2;
        // libFLAC 1.5.0 multiplies the whole block AFTER the decode,
        // stream_decoder.c:3028). The table records those same raw values
        // (the oracle walk reads s(subframe_bits) un-padded and pins
        // raw == pcm >> wasted at generation time). The OUTPUT prefix is
        // the padded value: §9.2.2's multiply lands at block exit, so
        // `out[..order]` equals raw << wasted == the block's own first
        // PCM samples.
        //
        // This assertion has been wrong in both directions: it once
        // compared padded state while the impl was mixed-scale (failed on
        // fixed1-wasted5-256, [20000] vs [625] — the *impl* was wrong
        // there), and compared padded state against the stripped-scale
        // impl once the scale contract landed (the *assertion* wrong
        // then). FLAC.md's "test bug, not impl bug" lesson, twice fired.
        let order = v.order as usize;
        let pad = |x: &i64| ((x << v.wasted as i64) as i32);
        assert_eq!(state.len, order, "{what}: state.len");
        let mrf: Vec<i32> = v
            .warm_up_stream_order
            .iter()
            .rev()
            .map(|x| *x as i32)
            .collect();
        assert_eq!(
            &state.warm_up[..order],
            &mrf[..],
            "{what}: warm-up state (coded scale, most-recent-first)"
        );
        let stream_order: Vec<i32> = v.warm_up_stream_order.iter().map(pad).collect();
        assert_eq!(
            &out[..order],
            &stream_order[..],
            "{what}: warm-up must double as the block's own first samples (padded)"
        );

        // 3. exit cursor — the oracle walk's exit position, relative to the
        // frame's first byte. This is the load-bearing witness for every
        // field width below the header.
        assert_eq!(
            reader.bit_position(),
            v.exit_bits as usize,
            "{what}: exit cursor must land exactly at the subframe body end \
             (before the frame footer, which is 3f's)"
        );

        // 4. samples vs the reference decoder, bit-exact
        let expect: Vec<i32> = v.pcm_samples.iter().map(|&x| x as i32).collect();
        assert_eq!(out.len(), expect.len(), "{what}: pcm length");
        assert_eq!(out, expect, "{what}: decoded samples != flac -d PCM");
    }
}

/// Bit offset of the LPC `u(4)` precision field, derived from the vector's
/// own witnessed fields — never hardcoded: header exit + pad/type (7) +
/// wasted field (flag 1 bit, plus `wasted` unary bits when set) + `order`
/// × `subframe_bits`. If any of those widths were wrong, the mutations
/// below would corrupt a different field and the *acceptance* test would
/// already fail on the unmutated vector — the same arithmetic the
/// exit-cursor witness pins.
fn lpc_precision_bit(v: &BodyVector) -> usize {
    assert_eq!(v.kind, "lpc", "{}: not an LPC vector", v.label);
    let (reader, _header) = frame_reader(v);
    let wasted_field_bits = if v.wasted == 0 {
        1
    } else {
        v.wasted as usize + 1
    };
    reader.bit_position() + 7 + wasted_field_bits + (v.order as usize) * (v.subframe_bits as usize)
}

/// Write `value`'s `n` MSB-first bits at bit `pos` of `buf` — the mutation
/// tool for rejection cases libFLAC can never witness.
fn write_bits(buf: &mut [u8], pos: usize, n: u32, value: u32) {
    for i in 0..n {
        let bit = (value >> (n - 1 - i)) & 1;
        let idx = pos + i as usize;
        let byte = &mut buf[idx >> 3];
        let mask = 0x80u8 >> (idx & 7);
        *byte = if bit == 1 {
            *byte | mask
        } else {
            *byte & !mask
        };
    }
}

/// Rejections with no encoder witness (libFLAC never emits them): mutate
/// ONE field of the real `lpc-256` frame, exactly as the header suites
/// mutate real headers. Each case asserts the specific variant, that the
/// rejection consumed zero bits behind the rejected field, and that no
/// residual sample was written.
#[test]
fn lpc_body_rejections_mutate_a_real_frame() {
    let v = load_body_vectors()
        .into_iter()
        .find(|v| v.kind == "lpc")
        .expect("body table must carry an lpc vector");
    let prec_pos = lpc_precision_bit(&v);
    let shift_pos = prec_pos + 4;
    let blocksize = v.blocksize as usize;
    let order = v.order as usize;

    // Control first: the unmutated frame decodes. This guards the derived
    // bit positions — a wrong position mutates the wrong field, and the
    // acceptance suite is the real witness; the control only catches the
    // gross cases (mutation landing in the warm-up, say).
    let (mut reader, header) = frame_reader(&v);
    let mut state = PredictorState::new();
    let mut out = vec![0i32; blocksize];
    decode_subframe(
        &mut reader,
        header.blocksize,
        header.bits_per_sample,
        &mut state,
        &mut out,
    )
    .expect("control: unmutated lpc-256 must decode");

    // Helper: decode a mutated frame, expecting `want` at `want_cursor`.
    // Parses THE MUTATED slice — the first draft re-parsed `v.frame` (the
    // unmutated vector) and every mutation "decoded fine", which is what
    // witness-shaped asserts are for: the disagreement was the bug.
    let probe = |frame: &[u8], want: Error, want_cursor: usize| {
        let mut reader = BitReader::new(frame);
        let header = FrameHeader::parse(&mut reader, &defaults(&v))
            .expect("mutations are below the header; the header must still parse");
        let mut state = PredictorState::new();
        let mut out = vec![0i32; blocksize];
        assert_eq!(
            decode_subframe(
                &mut reader,
                header.blocksize,
                header.bits_per_sample,
                &mut state,
                &mut out,
            ),
            Err(want),
            "mutation wanted {want:?}"
        );
        assert_eq!(
            reader.bit_position(),
            want_cursor,
            "{want:?} rejection must consume nothing behind the rejected field"
        );
        assert!(
            out[order..].iter().all(|&s| s == 0),
            "{want:?} rejection must write no residual samples"
        );
    };

    // §9.2.6 Table 22: precision code 0b1111 is forbidden.
    let mut frame = v.frame.clone();
    write_bits(&mut frame, prec_pos, 4, 0b1111);
    probe(&frame, Error::InvalidField, prec_pos + 4);

    // §9.2.6: the s(5) shift MUST NOT be negative. 0b10000 = −16.
    let mut frame = v.frame.clone();
    write_bits(&mut frame, shift_pos, 5, 0b10000);
    probe(&frame, Error::InvalidField, shift_pos + 5);
}
