//! # opus_spike — the Opus perf-gate spike (OPUS.md step 2: arms + witness)
//!
//! The go/no-go measurement vehicle OPUS.md's "Measurement plan — start here
//! (added 2026-09-29)" calls for: can a 16.78 MHz ARM7TDMI decode patched
//! `opus-rs` packets fast enough to keep a playback buffer fed? Roadmap +
//! rules: [`../../../OPUS.md`](../../../../OPUS.md).
//!
//! **PR 1 landed** the vendored patched `opus-rs`
//! (`vendor/opus-rs/`, patch inventory in `vendor/opus-rs/PATCHES.md`) wired
//! into a standalone crate, with the compile/link proof (`make
//! native-opus-rom`) and host pins (`make opus-test`). **PR 2 landed** the
//! two embedded arms — a SILK-only speech arm and a CELT-only music arm of
//! the same deterministic source ([`assets`], generated by
//! `scripts/gen_opus_assets.sh`, never hand-packed) — the sequential
//! manifest walk [`probe::decode_clip`], and the host decode witness
//! (`tests/opus_witness.rs`) proving the walk decodes the exact embedded
//! bytes onto the ffmpeg/libopus reference. **PR 3 (this step, IN
//! PROGRESS)** lands the **ROM decode proof** — the same walk executed
//! on-target over the embedded bytes, its folded PCM hashed against the
//! per-arm `fnv_walk_fold` golden (the vendored walk's own deterministic
//! output; the lossy codec cannot reuse flac_spike's reference-hash pin, see
//! `assets::OpusClip::fnv_walk_fold`) — with the decode state
//! heap-allocated in EWRAM, **plus the constructor-shape probe ROM**
//! (`src/ctor_probe.rs`, built beside the proof by `make opus-rom`). The
//! proof image is **red on-target with its mechanism proven**: the region
//! FNV matches, the walk banner prints, and the first decoder construction
//! dies — the ~178 KB by-value construction temporary puts SP at 0x02FAF610
//! (below IWRAM's bottom) in the construction frame, wrapping the ~31 KB
//! stack off IWRAM into mapped RAM until the corrupted return becomes a
//! wild jump (probe ROM readings, sha `0a358968…`; OPUS.md 2026-10-04
//! status entry). The host walk stays green — the failure is substrate-
//! specific. **What deliberately does NOT land here:** the constructor fix
//! (a construction path with no by-value hop — the next PR), and any cycle
//! counting (the harness arrives only once the proof is green,
//! correctness-before-speed, flac_spike PR 3's shape).
//!
//! Like the FLAC spike, this library is `#![no_std]` and shared by both
//! layers: the host tests (`make opus-test`) and the ROM entry (`src/main.rs`,
//! `make native-opus-rom`) consume the *same* [`probe`] seam, so the code the
//! later decode proof and cycle harness measure is the code the host witness
//! exercised. One structural difference from flac_spike, recorded up front:
//! Opus decode is a **state machine** — packets are not independently
//! decodable — so the future `decode_clip` walk is sequential per clip with a
//! fresh decoder, and the packet index is the product manifest, not a
//! seek-independence witness (OPUS.md, measurement plan item 3).

#![no_std]
#![forbid(unsafe_code)]
#![warn(missing_docs)]

// The decode seam heap-allocates the decoder state + window (the Box-via-
// `alloc` pattern OPUS.md gotcha 1 sketches): under agb the global
// allocator is EWRAM's block heap; on host it is the system allocator.
extern crate alloc;

pub mod assets;
pub mod checksum;
pub mod probe;
