//! # opus_spike — the Opus perf-gate spike (OPUS.md step 2: arms + witness)
//!
//! The go/no-go measurement vehicle OPUS.md's "Measurement plan — start here
//! (added 2026-09-29)" calls for: can a 16.78 MHz ARM7TDMI decode patched
//! `opus-rs` packets fast enough to keep a playback buffer fed? Roadmap +
//! rules: [`../../../OPUS.md`](../../../../OPUS.md).
//!
//! **PR 1 landed** the vendored patched `opus-rs`
//! (`vendor/opus-rs/`, patch inventory in `vendor/opus-rs/PATCHES.md`) wired
//! into a standalone crate, with the compile/link proof (`make
//! native-opus-rom`) and host pins (`make opus-test`). **PR 2 (this step)
//! lands:** the two embedded arms — a SILK-only speech arm and a CELT-only
//! music arm of the same deterministic source ([`assets`], generated by
//! `scripts/gen_opus_assets.sh`, never hand-packed) — the sequential manifest
//! walk [`probe::decode_clip`], and the host decode witness
//! (`tests/opus_witness.rs`) proving the walk decodes the exact embedded
//! bytes onto the ffmpeg/libopus reference. **What it deliberately does NOT
//! land:** the ROM decode proof and any cycle counting —
//! correctness-before-speed orders those next, exactly like flac_spike PRs
//! 2–3 ordered the FLAC gate.
//!
//! Like the FLAC spike, this library is `#![no_std]` and shared by both
//! layers: the host tests (`make opus-test`) and the ROM entry (`src/main.rs`,
//! `make native-opus-rom`) consume the *same* [`probe`] seam, so the code the
//! later decode proof and cycle harness measure is the code the host witness
//! exercised. One structural difference from flac_spike, recorded up front:
//! Opus decode is a **state machine** — packets are not independently
//! decodable — so the future `decode_clip` walk is sequential per clip with a
//! fresh decoder, and the packet index is the product manifest, not a
//! seek-independence witness (OPUS.md, measurement plan item 3).

#![no_std]
#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod assets;
pub mod checksum;
pub mod probe;
